### ISSUE TITLE
Error when simple-statistics is installed

### ISSUE THREAD

**Issue by robiso** [StephanStanisic/simple-statistics#1]
Everytime this plugin is enabled on PHP 7.2 (ea-php72), CENTOS 7.7.

Notice: Undefined property: stdClass::$themes in /home/wcms/public_html/index.php on line 807.

```
	public function getThemePluginRepos(string $type = self::THEMES_DIR): array
	{
		$db = $this->getDb();
		$array = (array)$db->config->defaultRepos->{$type};

                // line 807 below
	        $arrayCustom = (array)$db->config->customRepos->{$type};
                // line 807 above

		$data = $this->getJsonFileData($this->themesPluginsCachePath);
		$lastSync = $db->config->defaultRepos->lastSync;
		if (empty($array) || empty($data) || strtotime($lastSync) < strtotime('-1 days')) {
			$this->updateAndCacheThemePluginRepos();
			$array = (array)$db->config->defaultRepos->{$type};
		}

		return array_merge($array, $arrayCustom);
	}
```

**Comment by robiso** [comment]
Forgot to add:
- plugin still works normally
- only admin sees the above mentioned error

**Comment by StephanStanisic** [comment]
Hmm, weird. Also notifications are messed up because I didn't see your issue. Will look into this!

**Comment by StephanStanisic** [comment]
I am not able to reproduce this bug, not getting any notices. (running php with `error_reporting` set to `E_ALL`)

It is weird because the `getThemePluginRepos` function has nothing to do with the plugin.

Is the error only on install or with every page request?

**Comment by robiso** [comment]
Hey @StephanStanisic sorry for the late response. I don't seem to always receive a notification and not sure what has changed recently.

This is weird as it only happens on the official wcms website.
----
Edit: found the issue. I migrated the old (2.7.0) database.js to 3.0.0 and didn't do the correct order of JSON objects.

Took some trial and error to boil it down to the db. Now we know this is an edge case and doesn't need fixing.

Sorry for opening issues on your GH like there's no tomorrow. :) Gladly closing issue!
